// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.17020
//


/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IwizzService", Namespace="http://tempuri.org/")]
public partial class wizzService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetUserByEmailOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserByNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback ValidateUserCredOperationCompleted;
    
    private System.Threading.SendOrPostCallback IsUserNameFreeOperationCompleted;
    
    private System.Threading.SendOrPostCallback EmailFreeOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveDevDescriptionsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDevDescriptionOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAllStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserSessionsOperationCompleted;
    
    /// CodeRemarks
    public wizzService() {
        this.Url = "http://178.157.216.170:8733/WCFwizzGames/";
    }
    
    /// CodeRemarks
    public event GetUserByEmailCompletedEventHandler GetUserByEmailCompleted;
    
    /// CodeRemarks
    public event GetUserByNameCompletedEventHandler GetUserByNameCompleted;
    
    /// CodeRemarks
    public event CreateUserCompletedEventHandler CreateUserCompleted;
    
    /// CodeRemarks
    public event ValidateUserCompletedEventHandler ValidateUserCompleted;
    
    /// CodeRemarks
    public event ValidateUserCredCompletedEventHandler ValidateUserCredCompleted;
    
    /// CodeRemarks
    public event IsUserNameFreeCompletedEventHandler IsUserNameFreeCompleted;
    
    /// CodeRemarks
    public event EmailFreeCompletedEventHandler EmailFreeCompleted;
    
    /// CodeRemarks
    public event SaveDevDescriptionsCompletedEventHandler SaveDevDescriptionsCompleted;
    
    /// CodeRemarks
    public event GetDevDescriptionCompletedEventHandler GetDevDescriptionCompleted;
    
    /// CodeRemarks
    public event GetAllStatsCompletedEventHandler GetAllStatsCompleted;
    
    /// CodeRemarks
    public event GetUserStatsCompletedEventHandler GetUserStatsCompleted;
    
    /// CodeRemarks
    public event GetUserSessionsCompletedEventHandler GetUserSessionsCompleted;
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/GetUserByEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public UserModel GetUserByEmail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email) {
        object[] results = this.Invoke("GetUserByEmail", new object[] {
                    email});
        return ((UserModel)(results[0]));
    }
    
    /// CodeRemarks
    public void GetUserByEmailAsync(string email) {
        this.GetUserByEmailAsync(email, null);
    }
    
    /// CodeRemarks
    public void GetUserByEmailAsync(string email, object userState) {
        if ((this.GetUserByEmailOperationCompleted == null)) {
            this.GetUserByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByEmailOperationCompleted);
        }
        this.InvokeAsync("GetUserByEmail", new object[] {
                    email}, this.GetUserByEmailOperationCompleted, userState);
    }
    
    private void OnGetUserByEmailOperationCompleted(object arg) {
        if ((this.GetUserByEmailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserByEmailCompleted(this, new GetUserByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/GetUserByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public UserModel GetUserByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
        object[] results = this.Invoke("GetUserByName", new object[] {
                    name});
        return ((UserModel)(results[0]));
    }
    
    /// CodeRemarks
    public void GetUserByNameAsync(string name) {
        this.GetUserByNameAsync(name, null);
    }
    
    /// CodeRemarks
    public void GetUserByNameAsync(string name, object userState) {
        if ((this.GetUserByNameOperationCompleted == null)) {
            this.GetUserByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByNameOperationCompleted);
        }
        this.InvokeAsync("GetUserByName", new object[] {
                    name}, this.GetUserByNameOperationCompleted, userState);
    }
    
    private void OnGetUserByNameOperationCompleted(object arg) {
        if ((this.GetUserByNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserByNameCompleted(this, new GetUserByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/CreateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CreateUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mail, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
        object[] results = this.Invoke("CreateUser", new object[] {
                    name,
                    mail,
                    password});
        return ((string)(results[0]));
    }
    
    /// CodeRemarks
    public void CreateUserAsync(string name, string mail, string password) {
        this.CreateUserAsync(name, mail, password, null);
    }
    
    /// CodeRemarks
    public void CreateUserAsync(string name, string mail, string password, object userState) {
        if ((this.CreateUserOperationCompleted == null)) {
            this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
        }
        this.InvokeAsync("CreateUser", new object[] {
                    name,
                    mail,
                    password}, this.CreateUserOperationCompleted, userState);
    }
    
    private void OnCreateUserOperationCompleted(object arg) {
        if ((this.CreateUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ValidateUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mail, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
        object[] results = this.Invoke("ValidateUser", new object[] {
                    mail,
                    password});
        return ((string)(results[0]));
    }
    
    /// CodeRemarks
    public void ValidateUserAsync(string mail, string password) {
        this.ValidateUserAsync(mail, password, null);
    }
    
    /// CodeRemarks
    public void ValidateUserAsync(string mail, string password, object userState) {
        if ((this.ValidateUserOperationCompleted == null)) {
            this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
        }
        this.InvokeAsync("ValidateUser", new object[] {
                    mail,
                    password}, this.ValidateUserOperationCompleted, userState);
    }
    
    private void OnValidateUserOperationCompleted(object arg) {
        if ((this.ValidateUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/ValidateUserCred", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public UserModel ValidateUserCred([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
        object[] results = this.Invoke("ValidateUserCred", new object[] {
                    email,
                    password});
        return ((UserModel)(results[0]));
    }
    
    /// CodeRemarks
    public void ValidateUserCredAsync(string email, string password) {
        this.ValidateUserCredAsync(email, password, null);
    }
    
    /// CodeRemarks
    public void ValidateUserCredAsync(string email, string password, object userState) {
        if ((this.ValidateUserCredOperationCompleted == null)) {
            this.ValidateUserCredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserCredOperationCompleted);
        }
        this.InvokeAsync("ValidateUserCred", new object[] {
                    email,
                    password}, this.ValidateUserCredOperationCompleted, userState);
    }
    
    private void OnValidateUserCredOperationCompleted(object arg) {
        if ((this.ValidateUserCredCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ValidateUserCredCompleted(this, new ValidateUserCredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/IsUserNameFree", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void IsUserNameFree([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, out bool IsUserNameFreeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsUserNameFreeResultSpecified) {
        object[] results = this.Invoke("IsUserNameFree", new object[] {
                    name});
        IsUserNameFreeResult = ((bool)(results[0]));
        IsUserNameFreeResultSpecified = ((bool)(results[1]));
    }
    
    /// CodeRemarks
    public void IsUserNameFreeAsync(string name) {
        this.IsUserNameFreeAsync(name, null);
    }
    
    /// CodeRemarks
    public void IsUserNameFreeAsync(string name, object userState) {
        if ((this.IsUserNameFreeOperationCompleted == null)) {
            this.IsUserNameFreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserNameFreeOperationCompleted);
        }
        this.InvokeAsync("IsUserNameFree", new object[] {
                    name}, this.IsUserNameFreeOperationCompleted, userState);
    }
    
    private void OnIsUserNameFreeOperationCompleted(object arg) {
        if ((this.IsUserNameFreeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.IsUserNameFreeCompleted(this, new IsUserNameFreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/EmailFree", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void EmailFree([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mail, out bool EmailFreeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EmailFreeResultSpecified) {
        object[] results = this.Invoke("EmailFree", new object[] {
                    mail});
        EmailFreeResult = ((bool)(results[0]));
        EmailFreeResultSpecified = ((bool)(results[1]));
    }
    
    /// CodeRemarks
    public void EmailFreeAsync(string mail) {
        this.EmailFreeAsync(mail, null);
    }
    
    /// CodeRemarks
    public void EmailFreeAsync(string mail, object userState) {
        if ((this.EmailFreeOperationCompleted == null)) {
            this.EmailFreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailFreeOperationCompleted);
        }
        this.InvokeAsync("EmailFree", new object[] {
                    mail}, this.EmailFreeOperationCompleted, userState);
    }
    
    private void OnEmailFreeOperationCompleted(object arg) {
        if ((this.EmailFreeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EmailFreeCompleted(this, new EmailFreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/SaveDevDescriptions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SaveDevDescriptions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string who, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string desc, out bool SaveDevDescriptionsResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SaveDevDescriptionsResultSpecified) {
        object[] results = this.Invoke("SaveDevDescriptions", new object[] {
                    who,
                    desc});
        SaveDevDescriptionsResult = ((bool)(results[0]));
        SaveDevDescriptionsResultSpecified = ((bool)(results[1]));
    }
    
    /// CodeRemarks
    public void SaveDevDescriptionsAsync(string who, string desc) {
        this.SaveDevDescriptionsAsync(who, desc, null);
    }
    
    /// CodeRemarks
    public void SaveDevDescriptionsAsync(string who, string desc, object userState) {
        if ((this.SaveDevDescriptionsOperationCompleted == null)) {
            this.SaveDevDescriptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDevDescriptionsOperationCompleted);
        }
        this.InvokeAsync("SaveDevDescriptions", new object[] {
                    who,
                    desc}, this.SaveDevDescriptionsOperationCompleted, userState);
    }
    
    private void OnSaveDevDescriptionsOperationCompleted(object arg) {
        if ((this.SaveDevDescriptionsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveDevDescriptionsCompleted(this, new SaveDevDescriptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/GetDevDescription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GetDevDescription([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
        object[] results = this.Invoke("GetDevDescription", new object[] {
                    name});
        return ((string)(results[0]));
    }
    
    /// CodeRemarks
    public void GetDevDescriptionAsync(string name) {
        this.GetDevDescriptionAsync(name, null);
    }
    
    /// CodeRemarks
    public void GetDevDescriptionAsync(string name, object userState) {
        if ((this.GetDevDescriptionOperationCompleted == null)) {
            this.GetDevDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDevDescriptionOperationCompleted);
        }
        this.InvokeAsync("GetDevDescription", new object[] {
                    name}, this.GetDevDescriptionOperationCompleted, userState);
    }
    
    private void OnGetDevDescriptionOperationCompleted(object arg) {
        if ((this.GetDevDescriptionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDevDescriptionCompleted(this, new GetDevDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/GetAllStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wizzAppServer.Models")]
    public PlayerStats[] GetAllStats() {
        object[] results = this.Invoke("GetAllStats", new object[0]);
        return ((PlayerStats[])(results[0]));
    }
    
    /// CodeRemarks
    public void GetAllStatsAsync() {
        this.GetAllStatsAsync(null);
    }
    
    /// CodeRemarks
    public void GetAllStatsAsync(object userState) {
        if ((this.GetAllStatsOperationCompleted == null)) {
            this.GetAllStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllStatsOperationCompleted);
        }
        this.InvokeAsync("GetAllStats", new object[0], this.GetAllStatsOperationCompleted, userState);
    }
    
    private void OnGetAllStatsOperationCompleted(object arg) {
        if ((this.GetAllStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAllStatsCompleted(this, new GetAllStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/GetUserStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PlayerStats GetUserStats([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
        object[] results = this.Invoke("GetUserStats", new object[] {
                    name});
        return ((PlayerStats)(results[0]));
    }
    
    /// CodeRemarks
    public void GetUserStatsAsync(string name) {
        this.GetUserStatsAsync(name, null);
    }
    
    /// CodeRemarks
    public void GetUserStatsAsync(string name, object userState) {
        if ((this.GetUserStatsOperationCompleted == null)) {
            this.GetUserStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserStatsOperationCompleted);
        }
        this.InvokeAsync("GetUserStats", new object[] {
                    name}, this.GetUserStatsOperationCompleted, userState);
    }
    
    private void OnGetUserStatsOperationCompleted(object arg) {
        if ((this.GetUserStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserStatsCompleted(this, new GetUserStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwizzService/GetUserSessions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wizzAppServer.Models")]
    public PlayerSession[] GetUserSessions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
        object[] results = this.Invoke("GetUserSessions", new object[] {
                    name});
        return ((PlayerSession[])(results[0]));
    }
    
    /// CodeRemarks
    public void GetUserSessionsAsync(string name) {
        this.GetUserSessionsAsync(name, null);
    }
    
    /// CodeRemarks
    public void GetUserSessionsAsync(string name, object userState) {
        if ((this.GetUserSessionsOperationCompleted == null)) {
            this.GetUserSessionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserSessionsOperationCompleted);
        }
        this.InvokeAsync("GetUserSessions", new object[] {
                    name}, this.GetUserSessionsOperationCompleted, userState);
    }
    
    private void OnGetUserSessionsOperationCompleted(object arg) {
        if ((this.GetUserSessionsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserSessionsCompleted(this, new GetUserSessionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wizzAppServer.Models")]
public partial class UserModel {
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private string emailField;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string nameField;
    
    private string passwordField;
    
    private PlayerSession[] sessionsField;
    
    /// <remarks/>
    public System.DateTime DateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public PlayerSession[] Sessions {
        get {
            return this.sessionsField;
        }
        set {
            this.sessionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wizzAppServer.Models")]
public partial class PlayerSession {
    
    private double accuracyField;
    
    private bool accuracyFieldSpecified;
    
    private double deathsField;
    
    private bool deathsFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string identifyerField;
    
    private double kdrField;
    
    private bool kdrFieldSpecified;
    
    private double killsField;
    
    private bool killsFieldSpecified;
    
    private string playTimeField;
    
    private double shotsFiredField;
    
    private bool shotsFiredFieldSpecified;
    
    private double shotsHitField;
    
    private bool shotsHitFieldSpecified;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime stopTimeField;
    
    private bool stopTimeFieldSpecified;
    
    private int userIdField;
    
    private bool userIdFieldSpecified;
    
    /// <remarks/>
    public double Accuracy {
        get {
            return this.accuracyField;
        }
        set {
            this.accuracyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccuracySpecified {
        get {
            return this.accuracyFieldSpecified;
        }
        set {
            this.accuracyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double Deaths {
        get {
            return this.deathsField;
        }
        set {
            this.deathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeathsSpecified {
        get {
            return this.deathsFieldSpecified;
        }
        set {
            this.deathsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Identifyer {
        get {
            return this.identifyerField;
        }
        set {
            this.identifyerField = value;
        }
    }
    
    /// <remarks/>
    public double Kdr {
        get {
            return this.kdrField;
        }
        set {
            this.kdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KdrSpecified {
        get {
            return this.kdrFieldSpecified;
        }
        set {
            this.kdrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double Kills {
        get {
            return this.killsField;
        }
        set {
            this.killsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KillsSpecified {
        get {
            return this.killsFieldSpecified;
        }
        set {
            this.killsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
    public string PlayTime {
        get {
            return this.playTimeField;
        }
        set {
            this.playTimeField = value;
        }
    }
    
    /// <remarks/>
    public double ShotsFired {
        get {
            return this.shotsFiredField;
        }
        set {
            this.shotsFiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShotsFiredSpecified {
        get {
            return this.shotsFiredFieldSpecified;
        }
        set {
            this.shotsFiredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double ShotsHit {
        get {
            return this.shotsHitField;
        }
        set {
            this.shotsHitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShotsHitSpecified {
        get {
            return this.shotsHitFieldSpecified;
        }
        set {
            this.shotsHitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime StartTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime StopTime {
        get {
            return this.stopTimeField;
        }
        set {
            this.stopTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StopTimeSpecified {
        get {
            return this.stopTimeFieldSpecified;
        }
        set {
            this.stopTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wizzAppServer.Models")]
public partial class PlayerStats {
    
    private double accuracyField;
    
    private bool accuracyFieldSpecified;
    
    private double deathsField;
    
    private bool deathsFieldSpecified;
    
    private double kdrField;
    
    private bool kdrFieldSpecified;
    
    private double killsField;
    
    private bool killsFieldSpecified;
    
    private double lvLReachedField;
    
    private bool lvLReachedFieldSpecified;
    
    private string playTimeField;
    
    private int playerIDField;
    
    private bool playerIDFieldSpecified;
    
    private string playerNameField;
    
    private double shotsFiredField;
    
    private bool shotsFiredFieldSpecified;
    
    private double shotsHitField;
    
    private bool shotsHitFieldSpecified;
    
    /// <remarks/>
    public double Accuracy {
        get {
            return this.accuracyField;
        }
        set {
            this.accuracyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccuracySpecified {
        get {
            return this.accuracyFieldSpecified;
        }
        set {
            this.accuracyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double Deaths {
        get {
            return this.deathsField;
        }
        set {
            this.deathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeathsSpecified {
        get {
            return this.deathsFieldSpecified;
        }
        set {
            this.deathsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double Kdr {
        get {
            return this.kdrField;
        }
        set {
            this.kdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KdrSpecified {
        get {
            return this.kdrFieldSpecified;
        }
        set {
            this.kdrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double Kills {
        get {
            return this.killsField;
        }
        set {
            this.killsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool KillsSpecified {
        get {
            return this.killsFieldSpecified;
        }
        set {
            this.killsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double LvLReached {
        get {
            return this.lvLReachedField;
        }
        set {
            this.lvLReachedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LvLReachedSpecified {
        get {
            return this.lvLReachedFieldSpecified;
        }
        set {
            this.lvLReachedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
    public string PlayTime {
        get {
            return this.playTimeField;
        }
        set {
            this.playTimeField = value;
        }
    }
    
    /// <remarks/>
    public int PlayerID {
        get {
            return this.playerIDField;
        }
        set {
            this.playerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PlayerIDSpecified {
        get {
            return this.playerIDFieldSpecified;
        }
        set {
            this.playerIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PlayerName {
        get {
            return this.playerNameField;
        }
        set {
            this.playerNameField = value;
        }
    }
    
    /// <remarks/>
    public double ShotsFired {
        get {
            return this.shotsFiredField;
        }
        set {
            this.shotsFiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShotsFiredSpecified {
        get {
            return this.shotsFiredFieldSpecified;
        }
        set {
            this.shotsFiredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double ShotsHit {
        get {
            return this.shotsHitField;
        }
        set {
            this.shotsHitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShotsHitSpecified {
        get {
            return this.shotsHitFieldSpecified;
        }
        set {
            this.shotsHitFieldSpecified = value;
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetUserByEmailCompletedEventHandler(object sender, GetUserByEmailCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public UserModel Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UserModel)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetUserByNameCompletedEventHandler(object sender, GetUserByNameCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public UserModel Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UserModel)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void ValidateUserCredCompletedEventHandler(object sender, ValidateUserCredCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ValidateUserCredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ValidateUserCredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public UserModel Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UserModel)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void IsUserNameFreeCompletedEventHandler(object sender, IsUserNameFreeCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IsUserNameFreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal IsUserNameFreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public bool IsUserNameFreeResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// CodeRemarks
    public bool IsUserNameFreeResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void EmailFreeCompletedEventHandler(object sender, EmailFreeCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EmailFreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EmailFreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public bool EmailFreeResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// CodeRemarks
    public bool EmailFreeResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void SaveDevDescriptionsCompletedEventHandler(object sender, SaveDevDescriptionsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveDevDescriptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveDevDescriptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public bool SaveDevDescriptionsResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// CodeRemarks
    public bool SaveDevDescriptionsResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetDevDescriptionCompletedEventHandler(object sender, GetDevDescriptionCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDevDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDevDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetAllStatsCompletedEventHandler(object sender, GetAllStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAllStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAllStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public PlayerStats[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PlayerStats[])(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetUserStatsCompletedEventHandler(object sender, GetUserStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public PlayerStats Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PlayerStats)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetUserSessionsCompletedEventHandler(object sender, GetUserSessionsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserSessionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserSessionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public PlayerSession[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PlayerSession[])(this.results[0]));
        }
    }
}
